version: '3'

services:
  sensevoice:
    image: registry.cn-hangzhou.aliyuncs.com/lucklittleboy/sensevoice-oneapi:1.0
    container_name: sensevoice
    ports:
      - "8000:8000"
    volumes:
      - /home/iic:/app/iic
    environment:
      - DEVICE_TYPE=cpu
    restart: unless-stopped 